FROM cgr.dev/chainguard/nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY app.js /usr/share/nginx/html/app.js
COPY assets /usr/share/nginx/html/assets

EXPOSE 8080
